title: Crown of Skies
description: A transmedia worldbuilding project
baseurl: "/crownofskies"
url: "https://masroorshirgaonkar.github.io"
markdown: kramdown
collections:
  news:
    output: true
    permalink: /news/:year/:slug/
plugins:
  - jekyll-relative-links
  - jekyll-paginate
